### ISSUE TITLE
Dataset or feature specific issues / irregularities

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-paper#22]
This is just a record of some "quirks" that are dataset or feature specific. Feel free to edit and add to the list
Will work on making a more general version of this for public consumption

- StudyForrest is in German and has no ingested speech transcript
- Sherlock movie is present in the Sherock and and SherlockMerlin datasets, with different subjects. We're going to focus on the Sherlock dataset for the Sherlock task, and the Merlin task from the SherlockMerlin dataset.
- SchematicNarrative has no "tokenized" BERT features because there are independent stimuli within each run. 
See: https://github.com/neuroscout/neuroscout/issues/772
- Life dataset has no faces due to the nature of the stimuli

**Comment by rbroc** [comment]
@adelavega closing this as not relevant for the paper, but feel free to re-open/migrate if needed
