### ISSUE TITLE
(re)run analyses for final version of paper

### ISSUE THREAD

**Issue by rbroc** [neuroscout/neuroscout-paper#32]
**Single predictor models**:
- Should be all done

**Frequency analyses**:
- We need to look into which models to report, but probably something incremental
- Run on NNDB and Narratives
- Check consistency in estimators and if inconsistent rerun

**Shot-change**:
- Re-run on NNDB
- Check consistency in estimators and if inconsistent rerun

**Lancaster norms**:
- Rerun on NNDB and Narratives
- Check consistency in estimators and if inconsistent rerun

**FaceNet**:
- @adelavega extracts NNDB
- Run NNDB
- Check consistency in estimators and if inconsistent rerun

**AudioSet**:
- Run music on NNDB and Narratives (need to be extracted)
- Maybe explore couple of other features (selectively pick them from the ontology)
- Check results and make decision on whether to keep them
- If we keep them, check consistency in estimators and if inconsistent rerun

**BERT**:
- Drop if for now (play with it in separate projects, e.g., https://github.com/rbroc/eval-neuroscout-lm) '
- Drop the embeddings too, but that could also go in a separate project

------
Reading brain dataset:
- Ignore for now, but maybe run frequency on it after everything else is done.

**Comment by PeerHerholz** [comment]
Hi folks,

just saw this and wanted to ask if there's anything I could do to help (e.g. check models, maps, etc.)?
Additionally, if there's anything interesting in the [presentation](https://docs.google.com/presentation/d/1_2f_VAwwaRQr1x_itygF-rx3h8onns__gCkpe1sY9Ng/edit?usp=sharing) I gave a month ago (e.g. proof-of-principle searchlights, etc.) that could be a cool showcase (for the paper or some online resource), let me know!

Cheers, Peer

**Comment by adelavega** [comment]
Thanks for the offer! I think we need to decide if neuroscout audio analyses are fit for this paper or better off separately. 

Probably there's enough for it to be its own paper, but we can think about that. 

Maybe we can meet in ~2 weeks and would love to get your feedback

**Comment by PeerHerholz** [comment]
Yeah, sure thing, whatever works for y'all!
