### ISSUE TITLE
meta-analysis problem

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-paper#33]

**Comment by adelavega** [comment]
summary: afni meta-anaysis maps w/ all tasks look very weak, especially for RMS which should be solid and looks good at single dataset level (t-stats)

two possibilities:
1) nndb is on a different scale from other datasets, due to preprocessing differences (primarily) but also predictor scale differences (q: should we re-scale?)
  - look at time series for both
  - possibly rescale RMS for an NNDB task and take a look
2) nndb tasks on average have fewer subjects, and if that's a problem (i.e. higher variance), they may overly domiante meta-analysis
3) AFNI specific issue may lead to unstable PEs, with some very high value
  - find an example of this
  - exclude NNDB from meta-analysis to test if that's the primary cause of strange results

**Comment by jdkent** [comment]
nistats including "None" estimators (assuming they are nistats)
![nistats_nndb-no_none-yes](https://user-images.githubusercontent.com/12564882/136622381-bf88a165-3264-435e-8fe8-4cb2210f5b45.png)

**Comment by jdkent** [comment]
using the first available collection for every study (including nndb
![first_collections](https://user-images.githubusercontent.com/12564882/136623699-53bdd296-fc79-4a03-9cbf-3299f5b04316.png)
)

**Comment by jdkent** [comment]
first available collections without nndb
![first_collections_nndb-no](https://user-images.githubusercontent.com/12564882/136624163-42cabaf0-a4ee-4cc2-9d4d-9575663f95fd.png)

**Comment by jdkent** [comment]
the first available collection results with and without nndb are perfectly correlated, but differ in magnitude.
