### ISSUE TITLE
refine plotting utils

### ISSUE THREAD

**Issue by rbroc** [neuroscout/neuroscout-paper#48]
create utils for surface plots (at least for single-predictor models), we need more compact ways to visualize results

**Comment by satra** [comment]
@jsmentch may already have some scripts for this.

**Comment by jsmentch** [comment]
I've been using customized nilearn+hcp_utils to plot cifti files as flatmaps - happy to share or adapt these if helpful

**Comment by rbroc** [comment]
thanks @satra and @jsmentch! Working on it - may ask for your feedback in the coming days :)
