### ISSUE TITLE
change jupyter book build branch from jupyter_book to master?

### ISSUE THREAD

**Issue by PeerHerholz** [neuroscout/neuroscout-paper#78]
Hi folks,

I just noticed that we currently have the `jupyter book build` `workflow` set up in a way that the `jupyter book` only rebuilds if we push to the `jupyter_book``branch` which means that we would either need to do all the updates there or go via `master` - `jupyter_book`. We could just change that in the [workflow](https://github.com/neuroscout/neuroscout-paper/blob/f97815cbf804e198717035c78b5b203abbda4341/.github/workflows/book.yml#L7) to instead rebuild if things get `pushed` to `master`. WDYT?

**Comment by adelavega** [comment]
go for it buddy

**Comment by adelavega** [comment]
Excuse me?
